# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/atkalish/projects/chip8_emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/atkalish/projects/chip8_emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/atkalish/projects/chip8_emulator/CMakeFiles /home/atkalish/projects/chip8_emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/atkalish/projects/chip8_emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chip8_emulator

# Build rule for target.
chip8_emulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chip8_emulator
.PHONY : chip8_emulator

# fast build rule for target.
chip8_emulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/build
.PHONY : chip8_emulator/fast

chip8.o: chip8.cpp.o
.PHONY : chip8.o

# target to build an object file
chip8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/chip8.cpp.o
.PHONY : chip8.cpp.o

chip8.i: chip8.cpp.i
.PHONY : chip8.i

# target to preprocess a source file
chip8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/chip8.cpp.i
.PHONY : chip8.cpp.i

chip8.s: chip8.cpp.s
.PHONY : chip8.s

# target to generate assembly for a file
chip8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/chip8.cpp.s
.PHONY : chip8.cpp.s

eventhandler.o: eventhandler.cpp.o
.PHONY : eventhandler.o

# target to build an object file
eventhandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/eventhandler.cpp.o
.PHONY : eventhandler.cpp.o

eventhandler.i: eventhandler.cpp.i
.PHONY : eventhandler.i

# target to preprocess a source file
eventhandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/eventhandler.cpp.i
.PHONY : eventhandler.cpp.i

eventhandler.s: eventhandler.cpp.s
.PHONY : eventhandler.s

# target to generate assembly for a file
eventhandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/eventhandler.cpp.s
.PHONY : eventhandler.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/main.cpp.s
.PHONY : main.cpp.s

opdecoder.o: opdecoder.cpp.o
.PHONY : opdecoder.o

# target to build an object file
opdecoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/opdecoder.cpp.o
.PHONY : opdecoder.cpp.o

opdecoder.i: opdecoder.cpp.i
.PHONY : opdecoder.i

# target to preprocess a source file
opdecoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/opdecoder.cpp.i
.PHONY : opdecoder.cpp.i

opdecoder.s: opdecoder.cpp.s
.PHONY : opdecoder.s

# target to generate assembly for a file
opdecoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/opdecoder.cpp.s
.PHONY : opdecoder.cpp.s

sdlscreen.o: sdlscreen.cpp.o
.PHONY : sdlscreen.o

# target to build an object file
sdlscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/sdlscreen.cpp.o
.PHONY : sdlscreen.cpp.o

sdlscreen.i: sdlscreen.cpp.i
.PHONY : sdlscreen.i

# target to preprocess a source file
sdlscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/sdlscreen.cpp.i
.PHONY : sdlscreen.cpp.i

sdlscreen.s: sdlscreen.cpp.s
.PHONY : sdlscreen.s

# target to generate assembly for a file
sdlscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/sdlscreen.cpp.s
.PHONY : sdlscreen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chip8_emulator"
	@echo "... chip8.o"
	@echo "... chip8.i"
	@echo "... chip8.s"
	@echo "... eventhandler.o"
	@echo "... eventhandler.i"
	@echo "... eventhandler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... opdecoder.o"
	@echo "... opdecoder.i"
	@echo "... opdecoder.s"
	@echo "... sdlscreen.o"
	@echo "... sdlscreen.i"
	@echo "... sdlscreen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

